version: '3.1'

services:
  node:
    container_name: node
    build: '.'
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres 
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres: 
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes: 
      - postgres-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - '5433:5432'

volumes:
  postgres-data:

networks:
  app-connect:
    driver: bridge